### ISSUE TITLE
Bring back the Twisted client, por favor

### ISSUE THREAD

**Issue by theduderog** [simplegeo/python-simplegeo#9]
The implementation seemed pretty clean, sharing the vast majority of the code with the main client.  Why get rid of it?

**Comment by aguynamedben** [comment]
Hey,

Today we are publicly launching Storage, as well as a new, merged Python client that handles Storage, Context, and Places.  We had to bring a lot of client code in sync when this happened, and we simply didn't have time to test the Twisted client to meet today's launch.

There was not a concerted decision to explicitly remove Twisted support.  We may add back in Twisted support in the future.

As you said, since it re-uses the regular Python client so well, it would probably be pretty easy to get working again.  If you'd like to take a stab at it, the code is here: https://github.com/simplegeo/python-simplegeo/commit/e8e89aef585484311bcf019157f66e7bc22662c9 otherwise, we'll re-evaluate down the road.

Sorry for the inconvenience =(.  For what it's worth, older version of the client should still work with SimpleGeo Storage, just without the new layer management functions.

-Ben Standefer

**Comment by theduderog** [comment]
Hi Ben,

Thanks for the response and explanation.  I might be willing at some point to add if back if you guys don't.  However, I would definitely feel better about it if you guys responded to pull requests.  There have been 4 pull requests for this project sitting unanswered for months.

**Comment by aguynamedben** [comment]
That's a really good point.  This project has been kind of shared by our team at SimpleGeo, and diffusion of responsibility is a bitch.  Now, I'm pretty much owning this project and I'll make sure going forward that each pull request is carefully considered and responded to.

I plan on going through the pull requests in the next day or two and merging the appropriate ones.  I'll take a little time to reinstate the Twisted client, but no promises.  I'll keep posted here how it goes.  Thanks for understanding.

-Ben

**Comment by theduderog** [comment]
Great.  I'm happy to hear you're taking ownership of it.
